// <auto-generated />
using System;
using System.Text.Json;
using CoreLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreLedger.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260111074046_AddInstituicaoAndFundoVinculo")]
    partial class AddInstituicaoAndFundoVinculo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.Fundo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AceitaCripto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("aceita_cripto");

                    b.Property<string>("ClassificacaoAnbima")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("classificacao_anbima");

                    b.Property<string>("ClassificacaoCVM")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("classificacao_cvm");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoAnbima")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("codigo_anbima");

                    b.Property<string>("Condominio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("condominio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DataConstituicao")
                        .HasColumnType("date")
                        .HasColumnName("data_constituicao");

                    b.Property<DateOnly?>("DataInicioAtividade")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio_atividade");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Exclusivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exclusivo");

                    b.Property<string>("NomeCurto")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nome_curto");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_fantasia");

                    b.Property<decimal>("PercentualExterior")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("percentual_exterior");

                    b.Property<bool>("PermiteAlavancagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("permite_alavancagem");

                    b.Property<string>("Prazo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prazo");

                    b.Property<int>("ProgressoCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progresso_cadastro");

                    b.Property<string>("PublicoAlvo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("publico_alvo");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<bool>("Reservado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reservado");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("situacao");

                    b.Property<string>("TipoFundo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_fundo");

                    b.Property<string>("Tributacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tributacao");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<bool>("WizardCompleto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("wizard_completo");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_fundo_cnpj")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Situacao")
                        .HasDatabaseName("ix_fundo_situacao");

                    b.HasIndex("TipoFundo")
                        .HasDatabaseName("ix_fundo_tipo");

                    b.ToTable("fundo", "cadastros");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoClasse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<string>("CnpjClasse")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj_classe");

                    b.Property<string>("CodigoClasse")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_classe");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FundoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fundo_id");

                    b.Property<string>("NomeClasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_classe");

                    b.Property<int?>("OrdemSubordinacao")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_subordinacao");

                    b.Property<decimal?>("RentabilidadeAlvo")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("rentabilidade_alvo");

                    b.Property<bool>("ResponsabilidadeLimitada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("responsabilidade_limitada");

                    b.Property<bool>("SegregacaoPatrimonial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("segregacao_patrimonial");

                    b.Property<string>("TipoClasseFidc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_classe_fidc");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorMinimoAplicacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_minimo_aplicacao");

                    b.HasKey("Id");

                    b.HasIndex("FundoId")
                        .HasDatabaseName("ix_classe_fundo");

                    b.HasIndex("FundoId", "CodigoClasse")
                        .IsUnique()
                        .HasDatabaseName("ix_classe_codigo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("fundo_classe", "cadastros");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoPrazo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int?>("CalendarioId")
                        .HasColumnType("integer")
                        .HasColumnName("calendario_id");

                    b.Property<Guid?>("ClasseId")
                        .HasColumnType("uuid")
                        .HasColumnName("classe_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int?>("DiasCarencia")
                        .HasColumnType("integer")
                        .HasColumnName("dias_carencia");

                    b.Property<int>("DiasCotizacao")
                        .HasColumnType("integer")
                        .HasColumnName("dias_cotizacao");

                    b.Property<int>("DiasLiquidacao")
                        .HasColumnType("integer")
                        .HasColumnName("dias_liquidacao");

                    b.Property<bool>("DiasUteis")
                        .HasColumnType("boolean")
                        .HasColumnName("dias_uteis");

                    b.Property<Guid>("FundoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fundo_id");

                    b.Property<TimeOnly>("HorarioLimite")
                        .HasColumnType("time")
                        .HasColumnName("horario_limite");

                    b.Property<decimal?>("PercentualMinimo")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentual_minimo");

                    b.Property<bool>("PermiteParcial")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_parcial");

                    b.Property<string>("TipoPrazo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_prazo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorMinimo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_minimo");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId")
                        .HasDatabaseName("ix_prazo_classe");

                    b.HasIndex("FundoId")
                        .HasDatabaseName("ix_prazo_fundo");

                    b.HasIndex("FundoId", "ClasseId", "TipoPrazo")
                        .IsUnique()
                        .HasDatabaseName("ix_prazo_tipo")
                        .HasFilter("ativo = true");

                    b.ToTable("fundo_prazo", "cadastros");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoPrazoExcecao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<int>("DiasCotizacao")
                        .HasColumnType("integer")
                        .HasColumnName("dias_cotizacao");

                    b.Property<int>("DiasLiquidacao")
                        .HasColumnType("integer")
                        .HasColumnName("dias_liquidacao");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<long>("PrazoId")
                        .HasColumnType("bigint")
                        .HasColumnName("prazo_id");

                    b.HasKey("Id");

                    b.HasIndex("PrazoId")
                        .HasDatabaseName("ix_prazo_excecao_prazo");

                    b.ToTable("fundo_prazo_excecao", "cadastros");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoSubclasse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<Guid>("ClasseId")
                        .HasColumnType("uuid")
                        .HasColumnName("classe_id");

                    b.Property<string>("CodigoSubclasse")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_subclasse");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("NomeSubclasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_subclasse");

                    b.Property<int?>("Serie")
                        .HasColumnType("integer")
                        .HasColumnName("serie");

                    b.Property<decimal?>("TaxaAdministracaoDiferenciada")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("taxa_administracao_diferenciada");

                    b.Property<decimal?>("ValorMinimoAplicacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_minimo_aplicacao");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId")
                        .HasDatabaseName("ix_subclasse_classe");

                    b.HasIndex("ClasseId", "CodigoSubclasse")
                        .IsUnique()
                        .HasDatabaseName("ix_subclasse_codigo")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("fundo_subclasse", "cadastros");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoTaxa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<string>("BaseCalculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("base_calculo");

                    b.Property<Guid?>("ClasseId")
                        .HasColumnType("uuid")
                        .HasColumnName("classe_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataFimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("data_fim_vigencia");

                    b.Property<DateOnly>("DataInicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio_vigencia");

                    b.Property<int?>("DiaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_pagamento");

                    b.Property<Guid>("FundoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fundo_id");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("percentual");

                    b.Property<string>("PeriodicidadePagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("periodicidade_pagamento");

                    b.Property<string>("PeriodicidadeProvisao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("periodicidade_provisao");

                    b.Property<string>("TipoTaxa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_taxa");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorMaximo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_maximo");

                    b.Property<decimal?>("ValorMinimo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_minimo");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId")
                        .HasDatabaseName("ix_taxa_classe");

                    b.HasIndex("FundoId")
                        .HasDatabaseName("ix_taxa_fundo");

                    b.HasIndex("TipoTaxa")
                        .HasDatabaseName("ix_taxa_tipo");

                    b.HasIndex("FundoId", "ClasseId", "TipoTaxa", "Ativa")
                        .IsUnique()
                        .HasDatabaseName("ix_taxa_unica_ativa")
                        .HasFilter("ativa = true");

                    b.ToTable("fundo_taxa", "cadastros");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoTaxaPerformance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("FundoTaxaId")
                        .HasColumnType("bigint")
                        .HasColumnName("fundo_taxa_id");

                    b.Property<int>("IndexadorId")
                        .HasColumnType("integer")
                        .HasColumnName("indexador_id");

                    b.Property<bool>("LinhaDagua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("linha_dagua");

                    b.Property<int?>("MesCristalizacao")
                        .HasColumnType("integer")
                        .HasColumnName("mes_cristalizacao");

                    b.Property<string>("MetodoCalculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("metodo_calculo");

                    b.Property<decimal>("PercentualBenchmark")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("percentual_benchmark");

                    b.Property<string>("PeriodicidadeCristalizacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("periodicidade_cristalizacao");

                    b.HasKey("Id");

                    b.HasIndex("FundoTaxaId")
                        .IsUnique()
                        .HasDatabaseName("ix_taxa_performance_taxa");

                    b.HasIndex("IndexadorId")
                        .HasDatabaseName("ix_taxa_performance_indexador");

                    b.ToTable("fundo_taxa_performance", "cadastros");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoVinculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContratoNumero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contrato_numero");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<Guid>("FundoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fundo_id");

                    b.Property<int>("InstituicaoId")
                        .HasColumnType("integer")
                        .HasColumnName("instituicao_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<bool>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("principal");

                    b.Property<string>("TipoVinculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_vinculo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FundoId")
                        .HasDatabaseName("ix_vinculo_fundo");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("TipoVinculo")
                        .HasDatabaseName("ix_vinculo_tipo");

                    b.HasIndex("FundoId", "TipoVinculo")
                        .HasDatabaseName("ix_vinculo_vigente")
                        .HasFilter("data_fim IS NULL");

                    b.ToTable("fundo_vinculo", "cadastros");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.Instituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_instituicao_cnpj");

                    b.ToTable("instituicao", "cadastros");
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Code")
                        .HasColumnType("bigint")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NormalBalance")
                        .HasColumnType("integer")
                        .HasColumnName("normal_balance");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_code");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_accounts_type_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasDatabaseName("ix_account_types_description");

                    b.ToTable("account_types", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<JsonDocument>("DataAfter")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_after");

                    b.Property<JsonDocument>("DataBefore")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_before");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PerformedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("performed_by_user_id");

                    b.Property<string>("RequestId")
                        .HasColumnType("text")
                        .HasColumnName("request_id");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Calendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<bool>("DiaUtil")
                        .HasColumnType("boolean")
                        .HasColumnName("dia_util");

                    b.Property<int>("Praca")
                        .HasColumnType("integer")
                        .HasColumnName("praca");

                    b.Property<int>("TipoDia")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_dia");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_calendarios_data");

                    b.HasIndex("Praca")
                        .HasDatabaseName("ix_calendarios_praca");

                    b.HasIndex("Data", "Praca")
                        .IsUnique()
                        .HasDatabaseName("ix_calendarios_data_praca");

                    b.ToTable("calendarios", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.CoreJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_date");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("job_description");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_id");

                    b.Property<DateTime?>("RunningDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("running_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("Status");

                    b.ToTable("core_jobs", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Fund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("InceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("inception_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ValuationFrequency")
                        .HasColumnType("integer")
                        .HasColumnName("valuation_frequency");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("funds", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.HistoricoIndexador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("date")
                        .HasColumnName("data_referencia");

                    b.Property<decimal?>("FatorDiario")
                        .HasColumnType("decimal(20,12)")
                        .HasColumnName("fator_diario");

                    b.Property<string>("Fonte")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fonte");

                    b.Property<Guid?>("ImportacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("importacao_id");

                    b.Property<int>("IndexadorId")
                        .HasColumnType("integer")
                        .HasColumnName("indexador_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(20,12)")
                        .HasColumnName("valor");

                    b.Property<decimal?>("VariacaoPercentual")
                        .HasColumnType("decimal(12,8)")
                        .HasColumnName("variacao_percentual");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia")
                        .HasDatabaseName("ix_historicos_indexadores_data_referencia");

                    b.HasIndex("IndexadorId")
                        .HasDatabaseName("ix_historicos_indexadores_indexador_id");

                    b.HasIndex("IndexadorId", "DataReferencia")
                        .IsUnique()
                        .HasDatabaseName("ix_historicos_indexadores_indexador_data");

                    b.ToTable("historicos_indexadores", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Indexador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataBase")
                        .HasColumnType("date")
                        .HasColumnName("data_base");

                    b.Property<decimal?>("FatorAcumulado")
                        .HasColumnType("decimal(20,12)")
                        .HasColumnName("fator_acumulado");

                    b.Property<string>("Fonte")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fonte");

                    b.Property<bool>("ImportacaoAutomatica")
                        .HasColumnType("boolean")
                        .HasColumnName("importacao_automatica");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Periodicidade")
                        .HasColumnType("integer")
                        .HasColumnName("periodicidade");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlFonte")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_fonte");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_indexadores_ativo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_indexadores_codigo");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_indexadores_tipo");

                    b.ToTable("indexadores", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("isin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_securities_status");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("ix_securities_ticker");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_securities_type");

                    b.ToTable("securities", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("FundId")
                        .HasColumnType("integer")
                        .HasColumnName("fund_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("quantity");

                    b.Property<int?>("SecurityId")
                        .HasColumnType("integer")
                        .HasColumnName("security_id");

                    b.Property<DateTime>("SettleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settle_date");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trade_date");

                    b.Property<int>("TransactionSubTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_subtype_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FundId")
                        .HasDatabaseName("ix_transactions_fund_id");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_transactions_security_id");

                    b.HasIndex("SettleDate")
                        .HasDatabaseName("ix_transactions_settle_date");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_transactions_status_id");

                    b.HasIndex("TradeDate")
                        .HasDatabaseName("ix_transactions_trade_date");

                    b.HasIndex("TransactionSubTypeId")
                        .HasDatabaseName("ix_transactions_transaction_subtype_id");

                    b.HasIndex("FundId", "TradeDate")
                        .HasDatabaseName("ix_transactions_fund_trade_date");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.TransactionCreatedOutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_on");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("Status");

                    b.ToTable("transaction_created_outbox_message", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.TransactionIdempotency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TransactionId");

                    b.ToTable("transaction_idempotency", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.TransactionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("long_description");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("short_description");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ShortDescription")
                        .HasDatabaseName("ix_transaction_statuses_short_description");

                    b.ToTable("transaction_statuses", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.TransactionSubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("long_description");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("short_description");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ShortDescription")
                        .HasDatabaseName("ix_transaction_subtypes_short_description");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_transaction_subtypes_type_id");

                    b.ToTable("transaction_subtypes", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("long_description");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("short_description");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ShortDescription")
                        .HasDatabaseName("ix_transaction_types_short_description");

                    b.ToTable("transaction_types", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("auth_provider_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("AuthProviderId", "Provider")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoClasse", b =>
                {
                    b.HasOne("CoreLedger.Domain.Cadastros.Entities.Fundo", "Fundo")
                        .WithMany("Classes")
                        .HasForeignKey("FundoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fundo");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoPrazo", b =>
                {
                    b.HasOne("CoreLedger.Domain.Cadastros.Entities.FundoClasse", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoreLedger.Domain.Cadastros.Entities.Fundo", "Fundo")
                        .WithMany()
                        .HasForeignKey("FundoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Fundo");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoPrazoExcecao", b =>
                {
                    b.HasOne("CoreLedger.Domain.Cadastros.Entities.FundoPrazo", "Prazo")
                        .WithMany("Excecoes")
                        .HasForeignKey("PrazoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prazo");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoSubclasse", b =>
                {
                    b.HasOne("CoreLedger.Domain.Cadastros.Entities.FundoClasse", "Classe")
                        .WithMany("Subclasses")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoTaxa", b =>
                {
                    b.HasOne("CoreLedger.Domain.Cadastros.Entities.FundoClasse", "Classe")
                        .WithMany("Taxas")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoreLedger.Domain.Cadastros.Entities.Fundo", "Fundo")
                        .WithMany("Taxas")
                        .HasForeignKey("FundoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Fundo");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoTaxaPerformance", b =>
                {
                    b.HasOne("CoreLedger.Domain.Cadastros.Entities.FundoTaxa", "FundoTaxa")
                        .WithOne("ParametrosPerformance")
                        .HasForeignKey("CoreLedger.Domain.Cadastros.Entities.FundoTaxaPerformance", "FundoTaxaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLedger.Domain.Entities.Indexador", "Indexador")
                        .WithMany()
                        .HasForeignKey("IndexadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FundoTaxa");

                    b.Navigation("Indexador");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoVinculo", b =>
                {
                    b.HasOne("CoreLedger.Domain.Cadastros.Entities.Fundo", "Fundo")
                        .WithMany()
                        .HasForeignKey("FundoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLedger.Domain.Cadastros.Entities.Instituicao", "Instituicao")
                        .WithMany("Vinculos")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fundo");

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Account", b =>
                {
                    b.HasOne("CoreLedger.Domain.Entities.AccountType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.HistoricoIndexador", b =>
                {
                    b.HasOne("CoreLedger.Domain.Entities.Indexador", "Indexador")
                        .WithMany()
                        .HasForeignKey("IndexadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Indexador");
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("CoreLedger.Domain.Entities.Fund", "Fund")
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreLedger.Domain.Entities.Security", "Security")
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoreLedger.Domain.Entities.TransactionStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreLedger.Domain.Entities.TransactionSubType", "TransactionSubType")
                        .WithMany()
                        .HasForeignKey("TransactionSubTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("Security");

                    b.Navigation("Status");

                    b.Navigation("TransactionSubType");
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.TransactionIdempotency", b =>
                {
                    b.HasOne("CoreLedger.Domain.Entities.Transaction", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.TransactionSubType", b =>
                {
                    b.HasOne("CoreLedger.Domain.Entities.TransactionType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.Fundo", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Taxas");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoClasse", b =>
                {
                    b.Navigation("Subclasses");

                    b.Navigation("Taxas");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoPrazo", b =>
                {
                    b.Navigation("Excecoes");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.FundoTaxa", b =>
                {
                    b.Navigation("ParametrosPerformance");
                });

            modelBuilder.Entity("CoreLedger.Domain.Cadastros.Entities.Instituicao", b =>
                {
                    b.Navigation("Vinculos");
                });
#pragma warning restore 612, 618
        }
    }
}
